version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: "npm run dev"
    ports:
      - "4000:4000"
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./.env
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abdoyasser
      MYSQL_DATABASE: unit
      MYSQL_USER: abdoyasser
      MYSQL_PASSWORD: devpass
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  db-data:
