import dotenv from "dotenv";

dotenv.config();

const PORT = process.env.PORT || 3000;
const JWT_SECRET = process.env.JWT_SECRET as string;
const JWT_REFRESH_SECRET = process.env.JWT_REFRESH_SECRET as string;
const NODE_ENV = process.env.NODE_ENV as string;
const CLIENT_URL = process.env.CLIENT_URL as string;

const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME as string;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY as string;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_CLOUD_NAME as string;

const GOOGLE_AUTH_ID = process.env.GOOGLE_AUTH_ID;
const GOOGLE_AUTH_SECRET = process.env.GOOGLE_AUTH_SECRET;
const GOOGLE_AUTH_SERVER_CALLBACK = process.env.GOOGLE_AUTH_SERVER_CALLBACK;
const GOOGLE_AUTH_URL_SUCCESS = process.env.GOOGLE_AUTH_URL_SUCCESS;

const MICROSOFT_AUTH_ID = process.env.MICROSOFT_AUTH_ID;
const MICROSOFT_AUTH_SECRET = process.env.MICROSOFT_AUTH_SECRET;
const MICROSOFT_AUTH_SERVER_CALLBACK =
  process.env.MICROSOFT_AUTH_SERVER_CALLBACK;

export {
  PORT,
  JWT_SECRET,
  JWT_REFRESH_SECRET,
  NODE_ENV,
  CLIENT_URL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  GOOGLE_AUTH_ID,
  GOOGLE_AUTH_SECRET,
  GOOGLE_AUTH_SERVER_CALLBACK,
  GOOGLE_AUTH_URL_SUCCESS,
  MICROSOFT_AUTH_ID,
  MICROSOFT_AUTH_SECRET,
  MICROSOFT_AUTH_SERVER_CALLBACK,
};
